import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Font Awesome CDN for social icons */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link rel="icon" type="image/png" href="/img/logo_icon.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}

        {/* Social Sidebar */}
        <div className="social-sidebar">
          <a
            href="https://facebook.com/QuintessentialTechnologies"
            className="facebook"
            target="_blank"
            rel="noopener noreferrer"
          >
            <i className="fab fa-facebook-f"></i>
            <span className="ml-5">Facebook</span>
          </a>
          <a
            href="https://instagram.com/quintessentialtechnology"
            className="instagram"
            target="_blank"
            rel="noopener noreferrer"
          >
            <i className="fab fa-instagram"></i>
            <span className="ml-5">Instagram</span>
          </a>
          <a
            href="https://linkedin.com/company/quintessential-technologie"
            className="linkedin"
            target="_blank"
            rel="noopener noreferrer"
          >
            <i className="fab fa-linkedin-in"></i>
            <span className="ml-5">LinkedIn</span>
          </a>
          <a
            href="#schedule"
            className="meeting"
            target="_blank"
            rel="noopener noreferrer"
          >
            <i className="fa-solid fa-calendar-check"></i>
            <span className="ml-5">Schedule Meeting</span>
          </a>
          <a
            href="https://wa.me/971561289803"
            className="whatsapp"
            target="_blank"
            rel="noopener noreferrer"
          >
            <i className="fab fa-whatsapp"></i>
            <span className="ml-5">WhatsApp</span>
          </a>
        </div>
      </body>
    </html>
  );
}
